# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(a77e7675-29de-4bcc-8cc4-bbf43b01dc8e)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login
      echo "Create storage account"
      az storage account create  --name function-storage --location eastus --resource-group Default-AU
      az functionapp create --name demo-function --storage-account function-storage --consumption-plan-location eastus --resource-group Default-AU --os-type Windows --runtime dotnet